tasks:
  - init: |
      docker-compose -f .docker/docker-compose.yml pull
  - command: |
      docker-compose -f .docker/docker-compose.yml up && sudo bash .docker/scripts/fixmoodleowner.sh

ports:
  - port: 8080
    onOpen: ignore
  - port: 8080
    onOpen: open-browser
  - port: 8080
    onOpen: open-preview
  - port: 8080
    onOpen: ignore
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
