tasks:
  - init: |
      docker-compose -f .docker/docker-compose.yml pull
  - command: |
      docker-compose -f .docker/docker-compose.yml up

ports:
  - port: 8080
    onOpen: open-browser
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
